@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
package fi.jakojaannos.roguelite.engine.view.sprite.serialization;

import fi.jakojaannos.roguelite.engine.utilities.annotation.FieldsAreNonnullByDefault;
import fi.jakojaannos.roguelite.engine.utilities.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;